DROP TABLE IF EXISTS Access;
CREATE TABLE Access(
	ID_ACCESS INT IDENTITY(1,1),
	NM_ACCESS VARCHAR(15) NOT NULL
	PRIMARY KEY (ID_ACCESS)
);

DROP TABLE IF EXISTS Users;
CREATE TABLE USERS (
	ID_USER INT IDENTITY(1,1),
	NM_USER VARCHAR(50) NOT NULL,
	PS_USER VARCHAR(15) NOT NULL,
	ID_ACCESS INT NOT NULL,
	ACTIVE INT DEFAULT 0,
	PRIMARY KEY (ID_USER)
);

ALTER TABLE USERS
DROP CONSTRAINT IF EXISTS Fk_AccessUser;

ALTER TABLE USERS
ADD CONSTRAINT FK_AccessUser
FOREIGN KEY (ID_ACCESS) REFERENCES Access(ID_ACCESS);


INSERT INTO Access VALUES ('Administrator');
INSERT INTO Access VALUES ('Employee');

INSERT INTO USERS VALUES ('Victor', '1234',1, 1);
INSERT INTO USERS VALUES ('Barros', '4321',1, 2);

DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE CATEGORY (
	ID_CATEGORY INT IDENTITY (1,1),
	DS_CATEGORY VARCHAR(50),
	PRIMARY KEY (ID_CATEGORY)
);

DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE PRODUCT (
	ID_PRODUCT INT IDENTITY (1,1),
	DS_PRODUCT VARCHAR(50) NOT NULL,
	ID_CATEGORY INT,
	ACTIVE INT DEFAULT 0,
	PRIMARY KEY (ID_PRODUCT)
);

ALTER TABLE PRODUCT
DROP CONSTRAINT IF EXISTS Fk_CategoryProduct;

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_CategoryProduct
FOREIGN KEY (ID_CATEGORY) REFERENCES Category(ID_CATEGORY);

INSERT INTO CATEGORY VALUES ('Drinks'),('Foods'),('Cleaning');
INSERT INTO PRODUCT VALUES ('Beer',1,1),('Juice',1,1),('Sandwich',2,1),('Fruits',2,1),('Bleach',3,1),('Soap',3,1);